#!/usr/bin/env php
<?php
require __DIR__ .'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use App\Commands;

$application = new Application();

// ... register commands
$application->add(new Commands\Hello());

$application->run();